### ISSUE TITLE
Is this repo still actively maintained?

### ISSUE THREAD

**Issue by nlangellier** [liormizr/s3path#109]
Just curious since the last commit to the master branch was in March of this year (2022).

**Comment by liormizr** [comment]
Hi @nlangellier 
This project is still live and kicking :wink:

I didn't push new features for the last few months but I'm planning to come back and update with new version very soon.

We didn't had high severity issues for a while so I see why the project looks not active.

Your PR #108  looks very cool, I'll check it out and respond to it next week
Sorry for the delay

**Comment by nlangellier** [comment]
Thanks for the quick reply @liormizr. And take your time. Just happy to help out in any way I can.
