### ISSUE TITLE
Broken in Python 3.11

### ISSUE THREAD

**Issue by sbrandtb** [liormizr/s3path#112]
```
/usr/local/lib/python3.11/site-packages/s3path.py:12: in <module>
    from pathlib import _PosixFlavour, _Accessor, PurePath, Path
E   ImportError: cannot import name '_Accessor' from 'pathlib' (/usr/local/lib/python3.11/pathlib.py)
```

[The Accessor implementation was dropped](https://github.com/python/cpython/commit/08f8301b21648d58d053e1a513db8ed32fbf37dd) and S3path needs to support the new way of things :disappointed:

**Comment by cooperlees** [comment]
I feel you will have to gate code with checks of `sys.version_info >= (3, 11)` or something along the lines ...

It's probably also fine to start to dropping older versions. 3.6 is EOL and 3.7 is EOL in 6 months.

**Comment by liormizr** [comment]
Release in Version 0.4.0

**Comment by four43** [comment]
@liormizr  thanks so much for all the updates! Does v0.4.0 close this issue with Python 3.11?

**Comment by cooperlees** [comment]
bandersnatch's CI confirms this works for it's use case - Many thanks!

**Comment by liormizr** [comment]
@four43 yes, version 0.4.0 support Python 3.11
Thanks to @Darkheir

**Comment by four43** [comment]
Nice! Thank you all! It's appreciated

**Comment by sbrandtb** [comment]
Thanks a lot! Works like a charm and I could finally update my biggest project to 3.11 😄

**Comment by Darkheir** [comment]
> Thanks a lot! Works like a charm and I could finally update my biggest project to 3.11 smile

Thanks a lot for your feedback, I'm glad it helped other people :)

I tested it on several of my projects and I didn't see any issue, but it doesn't coverall the possible usage so it is cool to see other people that tested it !
