### ISSUE TITLE
Feature request: Support for S3 version IDs

### ISSUE THREAD

**Issue by nlangellier** [liormizr/s3path#126]
Hi @liormizr It would be nice to allow accessing specific versions of S3 objects for buckets that have enabled versioning.

This could be accomplished by adding an optional `version_id=None` argument to `PureS3Path.from_uri` and `PureS3Path.from_bucket_key` as well as defining `S3Path.__new__` like the following:
```python
def __new__(cls, *args, version_id=None, **kwargs):
    self = super().__new__(cls, *args, **kwargs)
    self.version_id = version_id
    return self
```

Then `_S3Accessor.open` would update the `transport_params` dict to include `path.version_id` if it is not `None`.

I already have a [working prototype](https://github.com/nlangellier/s3path/pull/4) ready for pull request if you approve of the idea.

What do you think?

**Comment by liormizr** [comment]
Hi @nlangellier 

Thanks for the feature request

Basically I don't have an issue adding S3 features as long that we are not changing the basic pathlib api and keeping our api as similar as posible

can you show me here what will be the change in the usage of s3path?

I'll give you example:
if we can add if versions are enable in the s3path.StatResult object that we get from [S3Path.state](https://github.com/liormizr/s3path/blob/master/s3path.py#L841)
And add a feature to call the specific version without changing the api that can work
We need to check the syntax but maybe something like this:
```
path = S3Path('/<bucket>/<key>?VersionID=<version_id>')
```

Does that make sense for you?

**Comment by nlangellier** [comment]
What I was suggesting would look like one of the following
```python
path = S3Path('/<bucket>/<key>', version_id='<version_id>')
path = S3Path.from_uri('s3://<bucket>/<key>', version_id='<version_id>')
path = S3Path.from_bucket_key(bucket='<bucket>', key='<key>', version_id='<version_id>')
```
This would only be an addition on top of the current API so the following would still work as usual:
```python
path = S3Path('/<bucket>/<key>')
path = S3Path.from_uri('s3://<bucket>/<key>')
path = S3Path.from_bucket_key(bucket='<bucket>', key='<key>')
```
But you are right that this would constitute a deviation from the `pathlib` API.

Are you implying with your suggestion of
```python
path = S3Path('/<bucket>/<key>?VersionID=<version_id>')
```
that we would parse the input S3 path string in a similar way that query params are parsed in a URL? If so I could certainly make that work. I would call out that '?' is a valid S3 object name character, but it is specifically [called out by AWS](https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-keys.html) as a character that might need special treatment, so perhaps it's OK. Thoughts?

**Comment by liormizr** [comment]
Thats exactly what I mean yes
We need to do small research, and check if we can add "?" like URL parsing
And what happens when adding "?" to a key - how s3path/boto3 react to it.
If the answer from this research is clear and explicit behaviour, we can go forward.
If not, need to think on a different approach.

**Comment by nlangellier** [comment]
@liormizr When implementing the `"?VersionId="` delimiter idea, it occurred to me that `pathlib.Path` has two methods of creating instances. `pathlib.Path("a/b/c.d")` produces the same object as `pathlib.Path("a", "b", "c.d")`. With the former, attaching `?VersionId=<version id>` to the end of the path string seems natural. But with the latter, it seems rather awkward. My opinion is that with this awkward nature and combined with the fact that `"/<bucket>/<key>?VersionId=<version id>"` has an edge case when either `<bucket>` or `<key>` actually contain the string `"?VersionId="`, that we should not use the `"?VersionId="` delimiter idea.

I would personally vote for the third option above (i.e. `class VersionedS3Path(S3Path):`). We already have precedent to extend the `pathlib` API in certain cases (e.g. `PureS3Path.from_uri` and `PureS3Path.from_bucket_key`) and this would just be one more such extension. As suggested in your earlier comment, I would make sure that `VersionedS3Path.stat` would behave as expected. WDYT?

**Comment by nlangellier** [comment]
Hi @liormizr #139 was just opened to address this feature request (co-authored between @chnpenny and myself) . Please have a look and review when you get a chance.

**Comment by liormizr** [comment]
We merged the PR
Tomorrow I'll upload a new version and update in this issue

**Comment by liormizr** [comment]
Deployed in version 0.5.0
