### ISSUE TITLE
Getting involved in the discussion on python.org about the extensibility of pathlib

### ISSUE THREAD

**Issue by gabrieldemarmiesse** [liormizr/s3path#130]
https://discuss.python.org/t/make-pathlib-extensible/3428

I think the owners of this project should voice their opinion/use cases/problems in this discussion, especially in the light of https://github.com/liormizr/s3path/issues/98 which highlight that shutil.copy doesn't work as expected for s3path.
The main post highlight very similar problems.

**Comment by liormizr** [comment]
Hi @gabrieldemarmiesse 
Thank for pointing me to this interesting discussion :-)
Wow very very coooool :-)
