### ISSUE TITLE
Remove S3DirEntry from `__all__`

### ISSUE THREAD

**Issue by gabrieldemarmiesse** [liormizr/s3path#134]
It seems it cannot be accessed from the public api, I don't know why it's there. Should we make it private?

**Comment by liormizr** [comment]
Hi @gabrieldemarmiesse 

You are right :-)

I'll clean it up

Thank you

**Comment by liormizr** [comment]
PR: #138

**Comment by liormizr** [comment]
Merged to master
I'll close this issue when we will deploy the next version

Tx

**Comment by liormizr** [comment]
Deployed in version 0.5.0

**Comment by cooperlees** [comment]
How is one meant to type making generators that return `_S3DirEntry` now `_S3DirEntry` is "private"?

PR upgrading bandersnatch to s3path to 0.5.0: https://github.com/pypa/bandersnatch/pull/1525
- We hit this here ...
