### ISSUE TITLE
Wrong type hint on S3Path factories inherited from PureS3Path

### ISSUE THREAD

**Issue by mgab** [liormizr/s3path#147]
When creating an S3Path from a `classmethod` factory inherited from PureS3Path, such as `from_uri`, the typing hint infers the result to be of type PureS3Path while in reality it's of type S3Path.

For example, doing

```Python
from s3path import S3Path, PureS3Path

a = PureS3Path.from_uri('s3://bucket/key/path')
# Revealed type is "s3path.PureS3Path"

b = S3Path.from_uri('s3://bucket/key/path')
# Revealed type is "s3path.PureS3Path"
```

While one would expect

```Python
from s3path import S3Path, PureS3Path

a = PureS3Path.from_uri('s3://bucket/key/path')
# Revealed type is "s3path.S3Path"

b = S3Path.from_uri('s3://bucket/key/path')
# Revealed type is "s3path.PureS3Path"
```

**Comment by liormizr** [comment]
Hi

I'll remove the type hint from the classmethods

**Comment by mgab** [comment]
Thanks @liormizr. I'd say there's no need though, in PR #148 I tried to make the changes so that the correct type is deduced also for subclasses

**Comment by liormizr** [comment]
@mgab I prefer to remove the hints from the classmethods
But thank you for your PR..

**Comment by liormizr** [comment]
New Version deployed 0.5.1 with this card fix
