### ISSUE TITLE
Using the library with S3 Compatible Storage

### ISSUE THREAD

**Issue by tekdubz** [liormizr/s3path#17]
Hi,
We are dealing with S3-Compatible Storage at work, to work with it, we use Boto and create a client or a resource and we specify the endpoint_url.

I'd love to be able to use s3path with my project, but from what I've seen I'm only able to use it with a "default session", the problem is that there is no such thing as a default session for custom endpoint.

Would it be possible to use your library with custom endpoints with a little bit of tweaking ?

Thanks,

**Comment by liormizr** [comment]
Hi @tekdubz 
You have 2 simple options as I see it:

1. using https://github.com/wbingli/awscli-plugin-endpoint.
you can see here a issue thread:
https://github.com/aws/aws-cli/issues/1270
from this issue thread looks like it should work...

2. modify s3path internals:
```
import boto3
import s3path

s3path._s3_accessor.s3 = boto3.resource('s3', endpoint_url=...)
```
After this change s3path will work with the new s3 resource in ALL your code.

Personally I like better the first option (if it works).
I don't like boto3 way of specifying configurations in the code...

Let me know if you need a more custom solution

**Comment by tekdubz** [comment]
Thanks !
I used option 2 (for testing, I will look into option 1 later), and it worked perfectly :+1:

**Comment by liormizr** [comment]
We created a formal way to integrate with S3-Compatible Storage
https://github.com/liormizr/s3path/blob/master/docs/advance.rst#s3-compatible-storage
