### ISSUE TITLE
Invalid escape sequence \Z

### ISSUE THREAD

**Issue by Alexander-Serov** [liormizr/s3path#174]
```
fitting.py:14: in <module>
    from s3path import PureS3Path, S3Path
.venv/lib/python3.8/site-packages/s3path/__init__.py:28: in <module>
    from .old_versions import (
E     File "/builds/project/.venv/lib/python3.8/site-packages/s3path/old_versions.py", line 76
E       new_regex_pattern += '/*\Z'
E                            ^
E   SyntaxError: invalid escape sequence \Z
```

Suggestion: mark [this](https://github.com/liormizr/s3path/blob/77868add45873495226ee96bf57e85c5ad82b104/s3path/old_versions.py#L76) as raw (r-) string: 
```
E       new_regex_pattern += r'/*\Z'
```
and the problem should be solved.

I only have it on some builds, so may depend on the python version used. All of my systems have 3.8.* but it fails only on some.

**Comment by liormizr** [comment]
I'll update here when deploying the next version with this fix

Thank you @Alexander-Serov for the fix

**Comment by Alexander-Serov** [comment]
@liormizr Sure!

**Comment by liormizr** [comment]
Version 0.5.8 deployed with the fix
