### ISSUE TITLE
ImportError: cannot import name 'Path' from 's3path' 

### ISSUE THREAD

**Issue by roserustowicz** [liormizr/s3path#178]
In the S3 vs boto usage example on downloading a file, the following line `from s3path import S3Path, Path` gives the error:
```
ImportError: cannot import name 'Path' from 's3path'
```

Link to the example: https://github.com/liormizr/s3path/blob/master/docs/comparison.rst

**Comment by liormizr** [comment]
Version 0.5.8 deployed with the fix
