### ISSUE TITLE
make conda installable and add to conda-forge

### ISSUE THREAD

**Issue by xguse** [liormizr/s3path#18]
It would make s3path easier to integrate into data science type projects if it was available through conda.

You can add a recipe to conda-forge: https://conda-forge.org/#add_recipe

**Comment by liormizr** [comment]
Hi @xguse tx for the idea!
Done.
https://anaconda.org/conda-forge/s3path

From now we can get s3path from:
conda install -c conda-forge s3path

Note: still need to update the README.rst

**Comment by xguse** [comment]
Spectacular! Thanks so much @liormizr !
