### ISSUE TITLE
Allow/Extend for explicit configuration of boto3.

### ISSUE THREAD

**Issue by milost** [liormizr/s3path#182]
Love the S3Path lib! Great job on creating such a useful lib for interacting with S3 storage.

Unfortunately, I am looking to connect to a MinIO server, which is S3-compatible but not AWS S3 itself. Is there any chance to extend the S3Path lib in a way that one could explicitly configure the connection, specifying which S3-compatible server to connect to?

This approach could have several advantages:
 * Increased flexibility: Users could work with various S3-compatible storage solutions, not just AWS S3.
* Support for on-premises storage: It would enable integration with locally hosted S3-compatible servers like MinIO.
* Broader adoption: The library could be used in more diverse environments and use cases.

**Comment by liormizr** [comment]
Hi @milost 
Nice to here that you like S3Path :-)

About MinIO, is this what you are looking for?
https://github.com/liormizr/s3path/blob/master/docs/advance.rst#s3-compatible-storage

**Comment by milost** [comment]
Hi,

I totally missed this! I'll give this a try right away! Thanks so much🙏🏻
