### ISSUE TITLE
MinIO Compatability

### ISSUE THREAD

**Issue by shyamd** [liormizr/s3path#20]
Any chance you'd be interested in switching over to something like MinIO's python client so this works with any S3 compatible object server?

https://github.com/minio/minio-py

**Comment by liormizr** [comment]
Hi @shyamd,

Good question.

First for a quick solution you can do this: https://github.com/liormizr/s3path/issues/17

In general I like the simplicity of s3path
Boto3 is the general AWS Python SDK library.
There for it's the latest and most updated library to communicate with AWS Services.
Also when I see issues in boto3 I open issue directly to AWS Python Developers...

**NOW** maybe it's time to open another project ;-)
"MinIOPath" or "ObjectServerPath" with MinIO driver in the "Accessor" class.
You can see the Boto3 Accessor here:
https://github.com/liormizr/s3path/blob/master/s3path.py#L61

What do you think? Are you interested to help in this kind of project?

**Comment by shyamd** [comment]
Oh! It looks like this is one way that even MinIO suggests using it: https://docs.min.io/docs/how-to-use-aws-sdk-for-python-with-minio-server.html

Modifying `_s3_accessor` will work fine for me in my project, but it might not be great as general usage. MinIO has immense popularity and a lot of other services are using it other S3 Compatible storage as a component. Both Google and Microsoft have S3 compliant access layers to their block storage. 

If my analysis is right , `_S3Acessor` is already ready to interact with non AWS S3 source since it passes `kwargs` to boto3. The issue is that parts of `S3Path` use `_s3_accessor` in the module which is an `_S3Acessor` initialized with no kwargs. I'm still trying to figure out how much of a problem this poses.

**Comment by liormizr** [comment]
We created a formal way to integrate with MinIO
https://github.com/liormizr/s3path/blob/master/docs/advance.rst#s3-compatible-storage

**Comment by shyamd** [comment]
Very cool! Thanks this is very useful. I think this issue is taken care of. I can close it if you want.
