### ISSUE TITLE
S3Path.write_bytes does not work

### ISSUE THREAD

**Issue by damonmaria** [liormizr/s3path#21]
Python 3.8
s3path: 0.1.8

Calling `write_bytes` on an `S3Path` fails as the `pathlib` `write_bytes` method wraps the data in a `memoryview`. S3Path's `_string_parser` then fails to detect and treat it as bytes / binary and therefore fails when calling `encode` on the data.

**Comment by liormizr** [comment]
PR for the fix: https://github.com/liormizr/s3path/pull/22

**Comment by liormizr** [comment]
fixed in version 0.1.9
And added tests for python 3.8

**Comment by liormizr** [comment]
updated Pypi and conda with 0.1.9

Enjoy

**Comment by damonmaria** [comment]
Hmmm.... not sure if I'm doing something wrong but I've upgraded (`pipenv upgrade`) and the changes listed in #22 aren't there. Viewing `site-packages/s3path.py` at the top is:
```python
__version__ = '0.1.09'
```

But further down `_string_parser` doesn't appear to be the new version:
```python
def _string_parser(text, *, mode, encoding):
    if isinstance(text, bytes):
        if 'b' in mode:
            return text
        return text.decode(encoding or 'utf-8')
    if 't' in mode or 'r' == mode:
        return text
    return text.encode(encoding or 'utf-8')
```

Just checking the what's published in Pypi is correct?

**Comment by liormizr** [comment]
Oops, sorry about that
Now looks good
version: 0.1.91 deployed

**Comment by damonmaria** [comment]
Tested and works. Thanks for being so responsive.
