### ISSUE TITLE
Officially support Python 3.8

### ISSUE THREAD

**Issue by impredicative** [liormizr/s3path#27]
Can this package be tested with Python 3.8, and it be added to [this list](https://github.com/liormizr/s3path/blob/f4360b9383741670bf8e3cc16f51d1c4d3098811/setup.py#L28-L31) in `setup.py`? Thanks.

**Comment by liormizr** [comment]
https://github.com/liormizr/s3path/pull/29

Hi @impredicative 
We are checking Python 3.8. you can see in [here](https://github.com/liormizr/s3path/blob/f4360b9383741670bf8e3cc16f51d1c4d3098811/.travis.yml#L5)

Thank you for pointing out the setup.py classifiers.
A new version (0.1.92) deployed to PyPi.
