### ISSUE TITLE
StatResult use wrong attribute names

### ISSUE THREAD

**Issue by impredicative** [liormizr/s3path#28]
@liormizr Why does `StatResult` use different attribute names than the ones used by [`pathlib`](https://docs.python.org/3/library/pathlib.html#pathlib.Path.stat) and [`os.stat_result`](https://docs.python.org/3/library/os.html#os.stat_result)? As a result, I cannot transparently use this package. I specifically need the `st_size` attribute but it's unavailable. This idiosyncrasy makes this package less than `pathlib` compatible. This concern is not limited to `st_size`.

**Comment by liormizr** [comment]
Hi @impredicative,

We thought about using the original os.stat_result object in the past,
But it wasn't trivial task so we created a new one.

The os.stat_result object have very FileSystem unix features that in the past we won't sure that we can translate to AWS S3 service so trivially.
For example:
What does this st_mode/st_gid mean in S3 service?
Or how many expensive queries to AWS you need to do to get st_atime...

In any case I see your point.
I'm added a st_size and st_mtime attributes.
We already have this data, and it's easy to convert to the right format.

If you need another attribute or in general have a good idea about the StatResult let us know

https://github.com/liormizr/s3path/pull/30
Deployed to PyPi version: 0.1.93

**Comment by impredicative** [comment]
Thanks. To summarize, it is okay for certain attributes to not be available, but all of the ones that are available should be `pathlib` compliant. This allows me to use a variety of paths transparently without special handling for s3path. I think we all understand.
