### ISSUE TITLE
Reliably publish to conda-forge as well

### ISSUE THREAD

**Issue by impredicative** [liormizr/s3path#31]
I see that [PyPI](https://pypi.org/project/s3path/#history) currently has v0.1.93 but [conda-forge](https://anaconda.org/conda-forge/s3path) has v0.1.91. Can the version on conda-forge be updated in tandem with the one on PyPI, or very close to it? Without this I cannot easily use the latest version in my conda environment. Thanks.

**Comment by liormizr** [comment]
Done
https://github.com/conda-forge/s3path-feedstock/pull/5
