### ISSUE TITLE
Support `endpoint_url` for localstack

### ISSUE THREAD

**Issue by waiyip-aquabyte** [liormizr/s3path#38]
We tests AWS locally using LocalStack.

This mean we instantiate boto3 resource with `endpoint_url` set to 'http://localhost:4566'. E.g.

`boto3.resource("s3", region_name=region, endpoint_url="http://localhost:4566")`

`boto3.setup_default_session` does not support `endpoint_url`.

The work around we are using is

```
    # pylint: disable=protected-access
    s3path._s3_accessor = s3path._S3Accessor(endpoint_url="http://localhost:4566")
```

This seems to work. It would be nice for it to be officially supported.

**Comment by liormizr** [comment]
We are working on an officially support, See #43 

We will update in the next version

@waiyip-aquabyte thanks for the issue, fill free to check out the Pull request and write your feedback

**Comment by liormizr** [comment]
deployed in version 0.2.201 enjoy
