### ISSUE TITLE
register_configuration_parameter is broken

### ISSUE THREAD

**Issue by waiyip-aquabyte** [liormizr/s3path#40]
```
from s3path import S3Path, register_configuration_parameter

bucket = S3Path('/bucket/')
register_configuration_parameter(bucket, parameters={'ContentType': 'text/html'})
bucket.joinpath('bar.html').write_text('hello')
```

Got this error

```
ValueError: too many values to unpack (expected 2)
```

**Comment by waiyip-aquabyte** [comment]
Also, is this a legit way to change how `write_text` behaves? The parameters should have only apply to `write_text` on this particular line only.

**Comment by waiyip-aquabyte** [comment]
Also the hierarchical configuration is broken

```
>>> p = S3Path('/foo/')
>>> register_configuration_parameter(p, parameters={'ContentType': 'text/html'})
>>> s3path._s3_accessor.configuration_map
{PosixPath('/'): {'ContentType': 'text/html'}}
```
 The config is registered with `/`. It is expected to be `/foo/`.

**Comment by liormizr** [comment]
Hi @waiyip-aquabyte thanks for the issues :-)
This is the fix for the hierarchical configuration - #42

Checking the rest

**Comment by liormizr** [comment]
Fixed the write issue as well
Will update with a new version

**Comment by liormizr** [comment]
deployed in version 0.2.201 enjoy
