### ISSUE TITLE
Support non-default session

### ISSUE THREAD

**Issue by maresb** [liormizr/s3path#45]
As far as I can tell, s3path [is hard-wired to use boto3's default session](https://github.com/liormizr/s3path/blob/6b17ee945eaa7d0f112f1a9b8ed1310b8dfc1944/s3path.py#L150). But I need to use a non-default session.

Actually, after further analysis of the source code, it looks like I could do
```python
from s3path import S3Path, register_configuration_parameter
register_configuration_parameter(S3Path("/"), resource=boto3.resource("s3"))
```
where above one can easily substitute a resource based on a user-defined session. But it took me a while of reading the code in order to figure this out. (I didn't find any corresponding documentation.) Am I doing it right?

Thanks for the great library!

**Comment by dannguyen** [comment]
Came here just to ask a variation of this; it'd be nice if S3Path could take in a `S3Uri` – e.g. `'s3://mybucket/path/to/object.file` – as used by the awscli S3 interface: https://docs.aws.amazon.com/cli/latest/reference/s3/#path-argument-type

**Comment by liormizr** [comment]
Hi Guys,

Right now (Version 0.2.201) this library documentation are pretty simple.
I'll be happy to hear how can we improve them...

In the main [README](https://github.com/liormizr/s3path/blob/master/README.rst) we can see some examples,
In the end of the README you can see three links with more details:

1. [pathlib style interface documentation](https://github.com/liormizr/s3path/blob/master/docs/interface.rst)
2. [comparison s3path vs boto3](https://github.com/liormizr/s3path/blob/master/docs/comparison.rst)
3. [advance features for Configurations](https://github.com/liormizr/s3path/blob/master/docs/advance.rst)

@dannguyen in the "pathlib style interface" page  you can see that we have two methods for handling uri's
[PureS3Path.as_uri](https://github.com/liormizr/s3path/blob/master/docs/interface.rst#pures3pathas_uri) and [PureS3Path.from_uri](https://github.com/liormizr/s3path/blob/master/docs/interface.rst#pures3pathfrom_uriuri)

@maresb in the "advance features for Configurations" page you can see register_configuration_parameter usage.

Please let me know if you have ideas how to simplify the doc's so it will be simpler to find everything.

**Comment by maresb** [comment]
@liormizr Thanks for the feedback. I am surprised that I didn't notice the third link in the README. I believe this was due to how it was formatted. I tried to provide you with a PR implementing the following suggestions, but I just spent about 30 minutes trying and failing to get GitHub to show custom link text with `.rst`.

I would replace the **Documentation** section with the following:

**Further Documentation**

* [Advanced S3Path configuration](https://github.com/liormizr/s3path/blob/master/docs/advance.rst) (S3 parameters, S3-compatible storage, etc.)
* [Abstract pathlib interface](https://github.com/liormizr/s3path/blob/master/docs/interface.rst) implemented by S3Path
* [pathlib documentation](https://docs.python.org/3/library/pathlib.html)
* [Boto3 vs S3Path usage examples](https://github.com/liormizr/s3path/blob/master/docs/comparison.rst)

**Comment by liormizr** [comment]
Hi @maresb I updated the README as you suggested 
Thanks for your feedback

**Comment by maresb** [comment]
Looks great, thanks!!!
