### ISSUE TITLE
writelines method is not compliant with base same method from file.

### ISSUE THREAD

**Issue by Darkheir** [liormizr/s3path#52]
To be compliant with the base `writelines` method the new line character should not be added.

From the documentation https://docs.python.org/2/library/stdtypes.html#file.writelines :

> The name is intended to match readlines(); writelines() does not add line separators.

There is also an issue where the double call to `_string_parser` (once in `writlines` and then in `write`) raising an error:

> TypeError: a bytes-like object is required, not 'str'

**Comment by liormizr** [comment]
Merged the fix, well done
I'll update when we will deploy a new version (2 days tops)

**Comment by liormizr** [comment]
Version 0.2.203 deployed with this fix

**Comment by liormizr** [comment]
@Darkheir is this issue still relevant or can we close it?

**Comment by Darkheir** [comment]
Yes we can close it. Thank you for the reactivity!
