### ISSUE TITLE
Issue in S3KeyReadableFileObject line iteration

### ISSUE THREAD

**Issue by Darkheir** [liormizr/s3path#53]
A few issues regarding the lines handling in `S3KeyReadableFileObject`:
* Everytime `readline` is called a new generator is created from `_streaming_body.iter_lines`
* The `__next__` method is calling `readline` and this method never raises `StopIteration`
* `readlines` is iterating over `readline` that  never raises `StopIteration`

**Comment by liormizr** [comment]
Merged the fix, well done
I'll update when we will deploy a new version (2 days tops)

**Comment by liormizr** [comment]
Version 0.2.203 deployed with this fix

**Comment by liormizr** [comment]
@Darkheir we can close this issue right?

**Comment by Darkheir** [comment]
Yes, we can close it! Thank you for your work !
