### ISSUE TITLE
Is there a changelog?

### ISSUE THREAD

**Issue by impredicative** [liormizr/s3path#54]
Going forward, I think it'll help to maintain a changelog. Without a changelog, it is in general more difficult to understand the notable changes from one released version to another.

**Comment by liormizr** [comment]
Hi @impredicative, I agree with you 100%!

Is there a way to do automation for deployment / release / tag / changelog?
Or do you think about jest a simple changelog file? 

In any case, can you help here with this task?

**Comment by impredicative** [comment]
Hi @liormizr 

Different people automate releases in different ways. I don't think there is one standard way afaik. In my Python package [bitlyshortener](https://github.com/impredicative/bitlyshortener), I have a [GitHub Action](https://github.com/impredicative/bitlyshortener/blob/3d412feb77f3daf6f71536463734c2119a55968d/.github/workflows/cicd.yml#L24-L45) which publishes to PyPI whenever I create a new release. In there I note the changelog in the release notes. For s3path though, there is also a conda release which is important, so that's an extra step in the release. In this way, at least I ensure clean releases, avoiding any release from my laptop. I see s3path is using travis and a Makefile.

In the changelog, I always type it manually, keeping it interesting for the end user. I skip information that is not relevant to the end user. Thank you.

**Comment by liormizr** [comment]
Thanks @impredicative 
I'll start to research about deployments with Travis
When we'll have a proper deployment process I'll add a proper changelog as well.

I'll update this card when I'll have something for feedback

**Comment by liormizr** [comment]
@impredicative we created a realese process
With automation deployment with Travis

From the next version we will have changelog :-)

See example [here](https://github.com/liormizr/s3path/releases)

**Comment by impredicative** [comment]
Looks nice.Is the version string updated manually?

https://github.com/liormizr/s3path/blob/c5e299eeaf41470c9f73abf10a688acb76b627eb/s3path.py#L25

Maybe it can be read from a file, and this file can be updated automatically during the release process. If it's manual, there is a chance of forgetting to update it, and then the publish to PyPI will fail.

In my package where I use a GitHub Action, I have it [read dynamically](https://github.com/impredicative/bitlyshortener/blob/3d412feb77f3daf6f71536463734c2119a55968d/setup.py#L23), although my use is different, and it wouldn't apply 1:1 here.

**Comment by liormizr** [comment]
Thanks for the feedback @impredicative 

Update the version automatically - I need to think about it
there are pros and cons to this approach
