### ISSUE TITLE
S3Path is awkward to use with boto and other libraries expecting bucket and key

### ISSUE THREAD

**Issue by markopy** [liormizr/s3path#55]
I was very excited about S3Path but after trying to use it in another project I have run into some issue which make it rather cumbersome. If you have a codebase which uses boto or need to interface with other libraries that use (bucket, key) pairs then things aren't straight forward.

The first issue is creating an S3Path from bucket and key strings. I was expecting to be able to simply do `S3Path(bucket, key)` or perhaps `S3Path(bucket=b, key=k)` but this creates a relative S3Path with no bucket.

I can use `S3Path('/', bucket, key)` which I guess is kind of OK until key starts with a slash in which case I just end up with `S3Path(/path1/path2/file)`, i.e. the first element of key becomes the bucket name which obviously makes no sense.

This behaviour might be for consistency pathlib but I think there should be straight forward way to make an S3Path from a bucket and key pair. If you don't care about python2 support perhaps an `__init__(*, bucket, key)` can be added which forces named arguments? Or a `from_bk(bucket, key)` class method like the existing `from_uri`?

The second issue is using S3Path with an api that expects bucket and key strings. The obvious thing to do, with for example boto, is `s3.upload_file('localfile', s3path.bucket, s3path.key)`. This doesn't work because boto expects str not S3Path. Fair enough, lets try `s3.upload_file('localfile', str(s3path.bucket), str(s3path.key))` ugly but perhaps reasonable, except that it doesn't work either because `s3path.bucket` starts with a slash. So to make it work you end up with `s3.upload_file('localfile', s3path.bucket.name, str(s3path.key))` which is not intuitive at all.

Is there a rational why `S3Path.bucket` and `S3Path.key` are S3Path objects instead of strings? To me they intuitively should give one the same (string) values expected from boto and other aws libraries. This would also be in line with how pathlib returns `.name`, `.suffix`, `.parts`, etc as strings.

I'm not really familiar with the internals of pathlib but purely based on the documentation it seems like conceptually the bucket name is something that should perhaps be treated more like `PurePath.drive` instead of just the first part of a posix path?

**Comment by impredicative** [comment]
Just a note: Changing the API would be a serious breaking change, and should not be done without first resolving #54 and then advancing a major version.

**Comment by markopy** [comment]
Certainly breaking the API needs to be carefully considered.

I'm currently using a subclass which adds `from_bk(bucket, key)` and `sbucket` / `skey` members. Arguably this just adds clutter compared to a clean API change though.

**Comment by impredicative** [comment]
> I'm currently using a subclass which adds from_bk(bucket, key)

Does `.from_uri(uri)` not work for your application?

**Comment by markopy** [comment]
> Does .from_uri(s3_uri) not work for your application?

It works if you format a string out of bucket and key but then you might as well use `S3path(f"/{bucket}/{key}")`. The whole point of using S3Path for me is to avoid having to do string manipulations of this kind.

**Comment by liormizr** [comment]
Hi Guys
@markopy thanks for starting this brainstorm.
Thinking about a proper api is one of my favorite things.

I agree with @impredicative, this is not the time to do breaking change.
And we still need to think about it.
converting bucket and key properties to string will solve your first issue
And if all the properties in pathlib returns string that is better

Remember the first goal of this library is to use the pathlib API without adding a lot of changes...

Now about the second issue
I have a suggestion.
In S3Path you can configure not only the bucket, key
We can set costume boto3 resource object and even custom kwargs to use when calling boto3 resource.

Please see [this](https://github.com/liormizr/s3path/blob/master/docs/advance.rst#advance-features-configurationss3-parameters) for more info.

What do you guys think about this:
```
register_configuration_parameter(S3Path('/'), parameters={'ServerSideEncryption': 'AES256'})

path = Path('/', 'bucket_name', 'key_name')
assert path.configuration == {
    'resource': boto3.resource,
    'parameters': {'ServerSideEncryption': 'AES256'},
    'key': 'key_name',
    'bucket': 'bucket_name',
)
```
In this case using boto3 can be like this:
```
config = path.configuration
s3.upload_file('localfile', config['bucket'], config['key'], **config['parameters'])
```

I already have something like this (Not in a clean way)
You can see it in the [configuration testing](https://github.com/liormizr/s3path/blob/master/tests/test_s3path_configuration.py)

What do you guys think?

BTW
I personally would have refactor that code to look like this:
```
local_path = PosixPath('localfile')
s3_path = S3Path(...)
s3_path.write_text(local_path.read_text())
``` 
But that's me ;-)

**Comment by markopy** [comment]
It would be neat to have a way to call boto with just something like
```
s3.upload_file('localfile', **path.botoparams)
```
which expands to `Bucket`, `Key` and any other appropriate parameters. However this would be limited to boto and not help with other code.

In my case I have a lot of legacy code I need to interface with and I can't convert it all to S3Path at once. Using
```
s3.upload_file('localfile', path.configuration['bucket'], path.configuration['key'])
```
is not really much of an improvement in my view, especially if I need to do some global configuration to get it to work. 

---
```
path = Path('/', 'bucket_name', 'key_name')
```
Just to reiterate, this is not a safe way to create an S3Path because it fails if key_name contains a leading slash.

---
```
local_path = PosixPath('localfile')
s3_path = S3Path(...)
s3_path.write_text(local_path.read_text())
```
Because it buffers everything in memory this doesn't work for larger files. I also ran into some failures using `open(mode='wb')` btw which I haven't debugged further. It also uses a temp file instead of directly uploading. I decided to be safe and just to back to boto which is why my example uses `upload_file()`

**Comment by impredicative** [comment]
Sorry but I don't have comments on specifying boto3 configuration options at this time, but it may be worthwhile to check other S3 Python packages, e.g. https://github.com/RaRe-Technologies/smart_open , to see how they permit the use of variable and multiple non-default configurations. I use both `s3path` and `smart_open`.

**Comment by liormizr** [comment]
OK
We just got an update from #39 
So Optimize the read/write big files is already in the queue

I'll work on that issue next and check here if it's enough for this case.

@markopy about the Path('/', 'bucket_name', 'key_name') example
I agree with you that it not safe

We can do something like this:

```
class PureS3Path():
    ...
    @classmethod
    def from_bucket_key(cls, bucket, key):
        bucket = bucket if isinstance(bucket, PureS3Path) else cls(bucket)
        key = key if isinstance(key, PureS3Path) else cls(key)
        if key.is_absolute():
            raise ValueError(...)
        return cls('/') / bucket / key
```

You think that this will present a better API?

We already added few methods in PureS3Path for S3 prepossess
I prefer not to add a lot of them but I'm open to here opinions

**Comment by markopy** [comment]
> ```
>     @classmethod
>     def from_bucket_key(cls, bucket, key):
>         bucket = bucket if isinstance(bucket, PureS3Path) else cls(bucket)
>         key = key if isinstance(key, PureS3Path) else cls(key)
>         if key.is_absolute():
>             raise ValueError(...)
>         return cls('/') / bucket / key
> ```
> 

I think this should have a check that bucket just contains one path element and not more.

Also it shouldn't fail if key is absolute. Technically S3 supports the actual key to begin with a slash, so `s3://foo//bar` is a different object from `s3://foo/bar`. Boto with default settings however normalizes the former to the later as does everyone else I think. So if key is absolute I think we should convert it to relative.

You don't really need to do the instance checks either, I think. How about (untested):
```
    @classmethod
    def from_bucket_key(cls, bucket, key):
        bucket = cls('/', bucket)
        if len(bucket.parts) != 2:
          raise ValueError(...)
        key = cls(key)
        if key.is_absolute():
            key = key.relative_to('/')
        return cls(bucket, key)
```

**Comment by liormizr** [comment]
Sorry for the delay

@markopy sounds good.
Do you want to do the contribution?

**Comment by markopy** [comment]
Sure, I can make a PR for `from_bucket_key` but can't promise an ETA so if someone needs it earlier just go for it.

Did you decide on what to do for the other direction? Accessing bucket and key as strings given an S3Path? I don't think `path.configuration['bucket']` is very nice, especially if it requires global configuration.

**Comment by liormizr** [comment]
@markopy 
I agree with you that `path.configuration['bucket']`  is not the best approach.
I think that the next step is optimization

rewriting the "S3 File objects" or using something like [smart_open](https://github.com/RaRe-Technologies/smart_open) or 
[s3fs](https://s3fs.readthedocs.io/en/latest/) will solve the issues

Writing it from scratch will keep our dependencies clean (Only boto3)
However using a well known library has it advantages...

If the pathlib API will work more efficiently it will be simpler to us a simpler API

What do you think about this strategy?

**Comment by markopy** [comment]
Using smart_open or another library to implement `open` makes sense but I'm not sure I understand the connection to this ticket. Accessing the bucket and key for a S3(Pure)Path seems entirely independent to file opening.

**Comment by liormizr** [comment]
@markopy yes you are right
I don't have a problem now to deploy a major version with a api change
So for this issue the changes are:

1. Adding  from_bucket_key classmethod
2. changing the bucket, key properties to return a string

@markopy is that something that you can add to your PR?

**Comment by liormizr** [comment]
Hi @markopy.
In the end I already implemented the agreed change.

Thanks for this interesting issue :-)

added in version 0.3.0
It's a big version, You can see the change log in Release [0.3.0](https://github.com/liormizr/s3path/releases/tag/0.3.0)

(Current version 0.3.01)
