### ISSUE TITLE
S3Path should keep newline characters in readline and readlines

### ISSUE THREAD

**Issue by Darkheir** [liormizr/s3path#56]
As written in the comment of the PR #50 `readline` and `readlines` methods should return the newline character if present to be compliant with the file interface

> f.readline() reads a single line from the file; a newline character (\n) is left at the end of the string, and is only omitted on the last line of the file if the file doesn’t end in a newline.

See https://docs.python.org/3/tutorial/inputoutput.html#methods-of-file-objects

This was a limitation because of the botocore `iter_lines` method in the `StreamingBody` class. But a PR to allow the method to return the newlines characters has been merged to the project: https://github.com/boto/botocore/pull/2235

It should now be possible to respect the file interface on this project.

**Comment by liormizr** [comment]
NIICE!!!!!!
Merging and I'll update here version when deployed

**Comment by liormizr** [comment]
Version 0.2.204 deployed
PyPi and Conda

**Comment by liormizr** [comment]
@Darkheir we can close this issue right?

**Comment by Darkheir** [comment]
Yes, thank you for your work !
