### ISSUE TITLE
Pandas compatibility

### ISSUE THREAD

**Issue by jose-moralez** [liormizr/s3path#59]
Hi. Thank you for making this package, it has helped me a lot and I use it almost interchangeably with `pathlib.Path`. The only friction I've found is when using an `S3Path` object as a filepath to `pandas.read_*`. I believe the relevant portion is [here](https://github.com/pandas-dev/pandas/blob/dae99c72b45cc74723ba71a5d9baab28411e6b50/pandas/io/common.py#L185), where `__fspath__` returns `__str__` which strips the `s3:/` prefix and tries to read from `/bucket` in the local file system. I tried overriding it but they're related and I get recursion errors haha. Do you have any suggestions for implementing this? I'd be happy to make a PR.

**Comment by liormizr** [comment]
Hi @jose-moralez ,
First thing thanks for the kind words :-)

what about calling the  `pandas.read_*` method with the file object?
For example:

```
path = S3Path('/<bucket>/<key>')
with path.open() as key_file:
    pandas.read_csv(key_file, ...)
```
or something like that
or do you have another idea?

**Comment by jose-moralez** [comment]
Thank you, that works very nicely. One more question, would there be a way to do something similar with a directory? Sometimes I use `s3path` with `dask.dataframe.read_*` functions, which can take a directory, that path gets resolved [here](https://github.com/intake/filesystem_spec/blob/fb406453b6418052f98b64d405bd4e6a4be1def1/fsspec/utils.py#L304) and they use the `__fspath__` attribute as well.

**Comment by liormizr** [comment]
So I don't think that it's a good idea to change the `__fspath__ ` method behavior
The idea of this project is that if you know pathlib API you can us aws s3 as the same way
Maybe you can do something like this:

```
path = S3Path('/<bucket>/<key-prefix>')
dask.dataframe. read_csv(path.as_uri())
```

Will this be cleaner for your case?

**Comment by jose-moralez** [comment]
Yes, this is what I'm currently doing, I have an if statement that does `as_uri()` for `S3Path` objects before passing them to the reading functions (both pandas and dask). Was just wondering if it would be possible to avoid but no worries, it's still very convenient in a lot of other places. I'm closing this since I most likely could use pandas all over the place with the `open` method you described above. Thanks again for this library!

**Comment by seanv507** [comment]
So I created a subclass of S3path overriding __fspath__ (to output self._as_uri()) to enable compatibility with pandas.
Any problem with this ?

I am testing ( against pandas ) mainly
