### ISSUE TITLE
Can't write to new object and use encoding 

### ISSUE THREAD

**Issue by johnml1135** [liormizr/s3path#64]
`my_s3_path.open("w", encoding="utf-8", newline="\n")`

This code will  produce the following error:
``` python
  File "C:\python\lib\site-packages\s3path.py", line 607, in open
    return self._accessor.open(
  File "C:\python\lib\site-packages\s3path.py", line 213, in open
    return file_object(
  File "C:\python\lib\site-packages\s3path.py", line 769, in __init__
    self._cache = NamedTemporaryFile(
  File "C:\python\lib\tempfile.py", line 542, in NamedTemporaryFile
    file = _io.open(fd, mode, buffering=buffering,
ValueError: binary mode doesn't take an encoding argument
```

It appears that the logic for the initialization of `S3KeyWritableFileObject` is the source of this error.  Specifically, this update should resolve it:
``` python
binary = 'b' if (('b' in self.mode) or (self.encoding is None)) else ''
self._cache = NamedTemporaryFile(
    mode=binary + self.mode.strip('b') + '+',
    buffering=self.buffering,
    encoding=self.encoding,
    newline=self.newline)
```

**Comment by liormizr** [comment]
Hi @johnml1135 thanks for the issue.
I was in the middle of version 0.3.0 that include a refactor of the file object to a more optimized and testes framework.

You can see the change log in Release [0.3.0](https://github.com/liormizr/s3path/releases/tag/0.3.0)

(Current version 0.3.01)
