### ISSUE TITLE
conda-forge recipe requirements

### ISSUE THREAD

**Issue by jose-moralez** [liormizr/s3path#67]
Hi. I recently ran into `NotImplementedError: cannot instantiate 'S3Path' on your system` when installing from conda-forge. The [docs](https://github.com/liormizr/s3path/blob/master/docs/interface.rst) indicate that this may be because `boto3` isn't installed but I had it so I struggled a bit and I think it's due to the new `smart-open` requirement.

I see that both `boto3` and `smart-open` are in `setup.py` so I think it'd be nice if they were included in the conda-forge recipe as well. I can make a PR there if you like.

**Comment by liormizr** [comment]
Hi @jose-moralez ,
Thanks for the issue.

It will be great if you can create a PR with a fix.

Tx

**Comment by liormizr** [comment]
PR: https://github.com/conda-forge/s3path-feedstock/pull/16 merged

**Comment by jose-moralez** [comment]
Just did a fresh install and verified that it works. Thanks!
