### ISSUE TITLE
Warning from smart_open

### ISSUE THREAD

**Issue by maresb** [liormizr/s3path#69]
I'm seeing the following warning. At the moment I don't have time to track it down, but maybe this is already enough to understand the problem?

```
/opt/conda/lib/python3.9/site-packages/smart_open/s3.py:220: UserWarning: ignoring the following deprecated transport parameters: ['multipart_upload_kwargs', 'object_kwargs', 'resource_kwargs', 'session']. See <https://github.com/RaRe-Technologies/smart_open/blob/develop/MIGRATING_FROM_OLDER_VERSIONS.rst> for details
  warnings.warn(message, UserWarning)
```

**Comment by maresb** [comment]
Ok, thanks. Then I assume it can be safely ignored.

**Comment by liormizr** [comment]
Next version I'll change the code that will behave according to the smart-ioen version.

I'll update here with version number when I'll finish

**Comment by liormizr** [comment]
Deployed
Version: 0.3.02
