### ISSUE TITLE
exists() fails when not the bucket owner

### ISSUE THREAD

**Issue by maresb** [liormizr/s3path#71]
[This SO comment describes the current bug](https://stackoverflow.com/questions/26871884/how-can-i-easily-determine-if-a-boto-3-s3-bucket-resource-exists#comment42356853_26876807). Namely that s3.buckets.all() returns only buckets owned by the current user. If the bucket is owned by someone else, exists() wrongly returns false.

**Comment by liormizr** [comment]
Looks great!
I merged the PR
Next version I'll change the code that will behave according to the smart-ioen version.

I'll update here with version number when I'll finish

**Comment by maresb** [comment]
Thanks so much for the quick response on this!

This was implicitly closed by the "closes" keyword in #72. Did you want to reopen this issue until the next release?

**Comment by liormizr** [comment]
Yes please

**Comment by liormizr** [comment]
Deployed
Version: 0.3.02
