### ISSUE TITLE
iterdir returns an S3Path for empty directories

### ISSUE THREAD

**Issue by backdoorbreaker** [liormizr/s3path#80]
When calling `iterdir()` on an empty `S3Path` object, a single path is still returned. This differs from the `pathlib.Path` behavior where `iterdir()` on an empty `Path` is an empty generator.

Example:
```
from s3path import S3Path
from pathlib import Path

s3p = S3Path("/path/to/empty/s3dir/")
p = Path("/path/to/empty/dir")

for child in s3p.iterdir():
    print(child)  # prints /path/to/empty/s3dir/

for child in p.iterdir():
    print(child)  # never prints
```

**Comment by liormizr** [comment]
Very interesting issue
Thank you for that...

PR: #81

I'll add this fix to the next version and update here when it will be deployed

**Comment by backdoorbreaker** [comment]
Awesome, thank you for the quick turnaround!

**Comment by liormizr** [comment]
Deployed
Version: 0.3.02
