### ISSUE TITLE
"compression" parameter is passed to smart_open.open() with incorrect version check

### ISSUE THREAD

**Issue by pd-nisse** [liormizr/s3path#89]
S3Path passes two different sets of kwargs to smart_open.open(), depending if version >=5.0.0 or lower. This throws an error when having smart_open=5.0.0 installed, because the parameter `compression` got only introduced in smart_open=5.1.0.

> TypeError: open() got an unexpected keyword argument 'compression'

https://github.com/RaRe-Technologies/smart_open/releases/tag/v5.1.0

Installing manually smart_open>=5.1.0 fixes this.

**Comment by liormizr** [comment]
Hi @pd-nisse ,

Thanks for the issue, I'll add a fix for the next version

PR: #91

**Comment by liormizr** [comment]
Deployed in version 0.3.3
